edit prod.yaml

diff --git a/.github/workflows/prod.yaml b/.github/workflows/prod.yaml
--- a/.github/workflows/prod.yaml
+++ b/.github/workflows/prod.yaml
@@ -15,8 +15,14 @@ jobs:
   DeploySimulation:
     runs-on: ubuntu-latest
     needs: BuildSimulation
-    steps:
+    steps:      
       - uses: actions/checkout@v3
+      - name: Check Release Manager
+        run: |
+            if [ "${{ github.actor }}" != "release-manager-username" ]; then
+            echo "Only the release manager is allowed to trigger this workflow. Aborting..."
+            exit 1
+          fi
       - name: Deploy
         run: |
           echo deploying into Test env
